---

- hosts: all
  become: true # enables sudo commands
  tasks:

  - name: install apache and php package
    package: # generic package manager (apt for Ubuntu, dnf for CentOS)
      name: 
        - "{{ apache_package }}" # the package to install (apt install <name>)
        - "{{ php_package }}"
      state: latest
      update_cache: true


