---

- hosts: all
  become: true # enables sudo commands
  tasks:

  - name: update repository index
    apt:
      update_cache: true

  - name: remove apache2 package
    apt: # the module to use
      name: apache2 # the package to install (apt install <name>)
      state: absent

  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
