---

- hosts: all
  become: true # enables sudo commands
  pre_tasks: # these tasks need to be run before anything else
  # both of the following tasks makes sure both CentOS and Ubuntu servers are fully up to date. Good to do always. 
  
  - name: update repository index (CentOS)
    tags: always
    dnf:
      # update_only: true # this doesn't need to be here because the bootstrap.yml does this already
      update_cache: true # still want to make sure the repository indexes are not stale (otherwise the playbook could fail)
    changed_when: false # doesn't consider this a "change". useful because this will change every time we run this playbook, so it keeps the output clear
    when: ansible_distribution == "CentOS"
  
  - name: update repository index (Ubuntu)
    tags: always
    apt:
      # upgrade: dist # this doesn't need to be here because the bootstrap.yml does this already
      update_cache: true # still want to make sure the repository indexes are not stale (otherwise the playbook could fail)
    changed_when: false # doesn't consider this a "change". useful because this will change every time we run this playbook, so it keeps the output clear
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
