---

- hosts: all
  become: true # enables sudo commands
  pre_tasks: # these tasks need to be run before anything else
  # both of the following tasks makes sure both CentOS and Ubuntu servers are fully up to date. Good to do always. 
  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: true
      update_cache: true
    when: ansible_distribution == "CentOS"
  
  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Ubuntu"
  
- hosts: web_servers # only against web_servers hosts
  become: true
  tasks:
  
  - name: install apache and php package (Ubuntu)
    tags: apache,apache2,ubuntu # tags are used to target plays which match the tags
    apt: # generic package manager (apt for Ubuntu, dnf for CentOS)
      name: 
        - apache2 # the package to install (apt install <name>)
        - libapache2-mod-php
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php package (CentOS)
    tags: apache,centos,httpd
    dnf:
      name: 
        - httpd
        - php
      state: present
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:
  
    - name: install mariadb package (CentOS)
      tags: centos,db,mariadb
      dnf:
        name: mariadb
        state: present
      when: ansible_distribution == "CentOS"
    
    - name: install mariadb package (Ubuntu)
      tags: db,mariadb,ubuntu
      apt:
        name: mariadb-server
        state: present
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: present


