- name: install apache and php package (Ubuntu)
  tags: apache,apache2,ubuntu # tags are used to target plays which match the tags
  apt: # generic package manager (apt for Ubuntu, dnf for CentOS)
    name: 
      - apache2 # the package to install (apt install <name>)
      - libapache2-mod-php
    state: present
  when: ansible_distribution == "Ubuntu"

- name: install apache and php package (CentOS)
  tags: apache,centos,httpd
  dnf:
    name: 
      - httpd
      - php
    state: present
  when: ansible_distribution == "CentOS"

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy: # copy files
    src: default_site.html # assumes subdir of `files/` under this role (`web_servers/files/`)
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644 # file permissions

- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service: # allows us to manage services on our linux servers
    name: httpd
    state: started # starts the service
    enabled: yes # enables the service
  when: ansible_distribution == "CentOS"

- name: change e-mail address for admin
  tags: apache,centos,httpd
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin sombody@somwhere.net
  when: ansible_distribution == "CentOS"
  register: httpd # capture the state in a variable

- name: restart httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: restarted # restarts the service
  when: httpd.changed # reference the variable that was registered above in "change e-mail address for admin". Thus, this will only run if the httpd is changed (i.e. the above play ran successfully)
