- name: install unzip
  package:
    name: unzip

- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.6.5/terraform_1.6.5_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes # tells ansible that this is a remote source and you don't need to search the files directory for it
    mode: 0755
    owner: root
    group: root